import cv2

# Map of threshold types
THRESHOLD_TYPE_MAP = {
    "THRESH_BINARY": cv2.THRESH_BINARY,
    "THRESH_BINARY_INV": cv2.THRESH_BINARY_INV,
    "THRESH_TRUNC": cv2.THRESH_TRUNC,
    "THRESH_TOZERO": cv2.THRESH_TOZERO,
    "THRESH_TOZERO_INV": cv2.THRESH_TOZERO_INV,
    "THRESH_MASK": cv2.THRESH_MASK,
    "THRESH_OTSU": cv2.THRESH_OTSU,
    "THRESH_TRIANGLE": cv2.THRESH_TRIANGLE,
    "THRESH_BINARY_OTSU": cv2.THRESH_BINARY + cv2.THRESH_OTSU  # Otsu's thresholding with binary thresholding
}
STRUCTURING_ELEMENT_TYPE_MAP = {
    "MORPH_RECT": cv2.MORPH_RECT,
    "MORPH_ELLIPSE": cv2.MORPH_ELLIPSE,
    "MORPH_CROSS": cv2.MORPH_CROSS
}